project:
  type: website
lang: nl

website:
  description: "Python voor KT"
  site-url: https://python-voor-kt.github.io
  title: "Python voor KT"
  navbar:
    background: primary
    foreground: white
    left:
      - href: index.qmd
        text: Handleidingen
      - links.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/python-voor-kt/python-voor-kt.github.io
format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    # Geldt voor de hele site. Kleur is $primary uit theme.scss.
    title-block-banner: "#00A6D6"
    title-block-banner-color: white



