project:
  type: website
lang: nl

website:
  description: "Python voor KT"
  site-url: https://python-voor-kt.github.io
  title: "Python voor KT"
  navbar:
    left:
      - manuals.qmd
      - links.qmd
      - articles.qmd
      - about.qmd
      - icon: github
        href: https://github.com/python-voor-kt/python-voor-kt.github.io
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



