---
title: "`uv` gebruiken als project-manager"
author: "Peter Somhorst"
---

`uv` is een project-manager voor Python projecten. Het zorgt voor 

- eenvoudige aanmaak en management van _virtual environments_;
- installatie van verschillende versies van Python;
- snelle installatie van Python-pakketten;
- aftemming van versies van _dependencies_;
- reproduceerbare installaties via een _lockfile_.

## Installatie
Installatie van `uv` is heel eenvoudig. Onderstaande instructies zijn gekopieerd uit de officiële documentatie van `uv`: <https://docs.astral.sh/uv/>. 

### macOS
Open een Terminal, en voer onderstaand command uit:

```bash
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Open daarna een nieuwe sessie in Terminal (of herstart de Terminal app).

### Windows
Open een PowerShell, en voer onderstaand commando uit:

```bash
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

Open daarna een nieuwe sessie in PowerShell (of herstart de PowerShell app).

## Project aanmaken

Het is aangeraden voor elk project (onderzoek, stage, vak, opdracht, spontaan idee) een nieuw `uv`-project aan te maken. Hier beschrijven we de methode die alleen gebruik maakt van de Terminal/PowerShell. Sommige programma's, waaronder Positron, hebben ook een eigen (eenvoudigere) manier om projecten aan te maken. 

::: {.callout-warning}
## OneDrive (Windows) en andere cloud-tools
Zet een `uv`-project **nooit** in OneDrive. Windows gebruikt OneDrive tegenwoordig als standaard locatie voor documenten. OneDrive werkt met 'cloudbestanden', die niet altijd daadwerkelijk op je computer staan. Zels als de bestanden wel op je computer staan, worden ze niet als normale bestanden behandeld.

Dit kan ook gelden voor bijvoorbeeld Dropbox. 

Een goede locatie is `C:\Users\<gebruikersnaam>\` (maar niet `C:\Users\<gebruikersnaam>\Documenten`).

Heb je wel eerder een project in OneDrive gezet, draai dan `uv cache clean` in je Terminal/PowerShell.
:::

### Nieuw project

Open een Terminal/PowerShell, en ga naar de bovenliggende map waarin je je project wil maken. Als de project-map `C:\Users\voorbeeld\Studie\programmeren\project-1` moet worden, ga je dus naar `C:\Users\voorbeeld\Studie\programmeren`. 

Draai daarna onderstaande code, waarbij je `<projectnaam>` vervangt met de naam van je project, in het voorbeeld hierboven dus `uv init project-1`. Dit maakt een nieuwe map, en zet daar de benodigde bestanden in. 

```bash
uv init <projectnaam>  
```

De naam van een projectmap moet starten met een letter, en mag alleen letters, cijfers, `-`, `_` en `.` (geen spaties) bevatten. 

::: {.callout-note}
## Python-versie

Standaard gebruikt `uv` de meest recente Python-versie voor het nieuwe project. Dit is meestal wenselijk. Soms, vooral als er net een nieuwe versie is vrijgegeven, is het wenselijk om een oudere (meer stabiele) versie te gebruiken. Je kunt een Python-versie kiezen door `--python <versie>` achter het `uv init`-commando te zetten, waarbij je `<versie>` vervangt door bijvoorbeeld `3.12` of `3.13.9`.
:::

### Bestaand project zonder `pyproject.toml`-bestand

Als je een bestaande projectmap hebt, maar nog geen `pyproject.toml`-bestand, volg dan deze instructies.

Open een Terminal/PowerShell, en ga naar de projectmap. Draai daarna onderstaande code. Dit maakt in deze map de benodigde bestanden aan.

```bash
uv init
```

Let op dat de naam van een projectmap moet starten met een letter, en alleen letters, cijfers, `-`, `_` en `.` (geen spaties) mag bevatten. 

### Bestaand project dat al een `pyproject.toml`-bestand heeft

Als je al een projectmap met een `pyproject.toml`-bestand hebt, volg dan deze instructies.

Open een Terminal/PowerShell, en ga naar de projectmap. Draai daarna onderstaande code. Dit vertelt `uv` dat je al een project hebt, en om een _virtual environment_ aan te maken op basis van het `pyproject.toml`-bestand.


```bash
uv sync
```

Let op dat de naam van een projectmap moet starten met een letter, en alleen letters, cijfers, `-`, `_` en `.` (geen spaties) mag bevatten. 

::: {.callout-note}
## _Virtual environments_
Een virtuele omgeving (_virtual environment_, vaak afgekort met _venv_) is een arparte 'virtuele' installatie van een specifieke versie van Python. Hierin installeer je alle Python-pakketten die je voor een project nodig hebt. Dit zorgt ervoor dat je de juiste versies van alle _dependencies_ installeert voor het juiste project. Als je voor Project A bijvoorbeeld een pakket nodig hebt die een 'oudere' versie van NumPy (<2.0) gebruikt, en Project B juist gebruik wil maken van de nieuwste mogelijkheden van Numpy (2.0 of nieuwer), kunnen deze projecten niet gebruik maken van dezelfde installaties. Door ze beiden in een eigen _virtual environment_ te draaien, heb je dit probleem niet.
:::

## Pakketten installeren

Je kunt paketten aan je installatie toevoegen met onderstaand commando, waarbij je `<naam>` vervangt door de naam van het pakket. Je kunt meerdere paketten toevoegen door meerdere namen achter elkaar te plaatsen, bijvoorbeeld `uv add numpy scipy matplotlib pandas`.

```bash
uv add <naam>
```

`uv` voegt het pakket toe aan de lijst met *dependencies* in `pyproject.toml`, en installeert het pakket en al zijn *dependencies*. 

Je kunt ook pakketten installeren met `uv pip add <naam>`. Dit installeert een pakket wel, maar voegt het niet toe aan de *dependencies* van het project. Daarmee is de installatie niet reproduceerbaar. Dit kan nuttig zijn om bijvoorbeeld een pakket uit te proberen, of tijdelijk te installeren en daarna weer te verwijderen. 

::: {.callout-note}
## _Dependencies_
Python-projecten maken meestal gebruik van andere Python-pakketten. Dit heet een _dependency_. Als je bijvoorbeeld `matplotlib` installeert, worden er ook negen _dependencies_, pakketten waar matplotlib gebruik van maakt, geïnstalleerd. Eén van deze pakketten heeft weer een eigen _dependency_, die ook wordt geïnstalleerd. Dit heet samen een _dependency tree_. Met het terminal-commando `uv tree` kan je deze voor je eigen project weergeven.

Bij installatie van pakketten is het belangrijk dat alle pakketten in de _dependecy tree_ goed met elkaar samenwerken. Het kan bijvoorbeeld zijn dat pakket A en pakket B beiden pakket C als _dependency_ hebben, waarbij pakket A kan werken met pakket C versie 1.2 tot 2.7, terwijl pakket B werkt met pakket C versie 2.0 tot 3.1. Een goede project-manager zorgt voor goede afstemming tussen versies, en stopt de installatie als er geen afstemming mogelijk is.[^pipdeps]

[^pipdeps]: De standaard manier om Python-pakketten te installeren, `pip`, zorgt niet voor afstemming tussen versies, maar installeert een versie die werkt voor het meest recent geïnstalleerde pakket. Dit kan soms tot problemen leiden.
:::

::: {.callout-note}
## _lockfile_
`uv` maakt voor geïnstalleerde projecten altijd een _lockfile_ aan. Hierin staat nauwkeurig beschreven welke versie van elk pakket in het project gebruikt is. Hierdoor kan de _virtual environment_ exact gereproduceerd worden op dezelfde én andere computers.
:::